version: '3.8'

services:
  ttm_front:
    build: ./ttm_frontend
    command: gunicorn main:app -b 0.0.0.0:1034
    volumes:
      - ./front:/ttm_front
    ports:
      - 1034:1034
    container_name: ttm_frontend
  ttm_db:
    image: mysql:latest
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: textToMeDB
      MYSQL_DATABASE: default
      MYSQL_USER: user
      MYSQL_PASSWORD: ttm12345
    container_name: ttm_db