version: '3.8'

services:
   ttm-front:
     build: ./ttm_frontend
     command: gunicorn main:app -b 0.0.0.0:1034
     volumes:
       - ./front:/ttm_front
     ports:
       - 1034:1034
     container_name: ttm_frontend
     depends_on:
       - ttm-back
  ttm-db:
    image: mysql:latest
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: textToMeDB
      MYSQL_DATABASE: default
      MYSQL_USER: user
      MYSQL_PASSWORD: ttm12345
    container_name: ttm_db
   ttm-back:
     build: ./ttm_backend
     ports:
       - "9453:8080"
     environment:
       - SPRING_DATASOURCE_URL=jdbc:mysql://ttm-db:3306/default
       - SPRING_DATASOURCE_USERNAME=user
       - SPRING_DATASOURCE_PASSWORD=ttm12345
     depends_on:
       - ttm-db
     container_name: ttm_backend
